console:
  max_message_size_bytes: 409600
  username: admin
  password: password
logger:
  format: json
  level: info
  stdout: true
runtime:
  js_entrypoint: "./main.js"
session:
  token_expiry_sec: 7200 # 2 hours
socket:
  max_message_size_bytes: 4096 # reserved buffer
  max_request_size_bytes: 131072
database:
  address:
    - "postgres:localdb@localhost:5432/nakama?sslmode=disable"
